name: WhateverBox Engine
on:
  push:
    branches: [ main ]
jobs:
  run-bridge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Start Engine
        env:
          TG_API_ID: ${{ secrets.TG_API_ID }}
          TG_API_HASH: ${{ secrets.TG_API_HASH }}
          SESSION_STRING: ${{ secrets.SESSION_STRING }}
          BOX_ID: ${{ secrets.BOX_ID }}
        run: python wb-engine/main.py
